name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        minecraft-version: [
          "1.20-R0.1-SNAPSHOT",
          "1.20.1-R0.1-SNAPSHOT",
          "1.20.2-R0.1-SNAPSHOT",
          "1.20.3-R0.1-SNAPSHOT",
          "1.20.4-R0.1-SNAPSHOT"
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify gradle
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with gradle
        run: ./gradlew build -PpaperweightDevBundleVersion=${{ matrix.minecraft-version }}

      - name: Upload for release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: "build/libs/*[!dev].jar"
